// <auto-generated />
using System;
using CourseApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CourseApp.Data.Course", b =>
                {
                    b.Property<int>("courseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("courseName")
                        .HasColumnType("TEXT");

                    b.HasKey("courseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseApp.Data.CourseRegister", b =>
                {
                    b.Property<int>("courseRegisterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("courseID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("courseRegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("studentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("courseRegisterID");

                    b.ToTable("CourseRegisters");
                });

            modelBuilder.Entity("CourseApp.Data.Student", b =>
                {
                    b.Property<int>("studentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("studentMail")
                        .HasColumnType("TEXT");

                    b.Property<string>("studentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("studentPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("studentSurname")
                        .HasColumnType("TEXT");

                    b.HasKey("studentID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
